### PR TITLE
Change private constructor to public

### PR DESCRIPTION
**Pull request by jgerszty**
Updated the, for some reason, `private` constructor to be `public`. Addresses issue #18

### CODE REVIEW

**Comment by ajcallos** [comment]
Reject change. Leaves createChecking unmodified, which calls Checking(String name); if Checking is changed to public, there is no reason for createChecking to exist.

**Comment by jgerszty** [comment]
Removed the method.

**Comment by ajcallos** [comment]
Looks good.

**Comment by jgerszty** [comment]
There is no good way to rename branches, this was the best we had. The branches have the same content.

**Pull request merged**
